module.exports = {
        "signup":{
            "site_url":"%site_url%",
            "encrypted_user_id":"%encrypted_user_id%",
            "name_param":"%name%",
            "year_param":"%current_year%"
        },
        "signin":{
            "site_url":"%site_url%",
            "name_param":"%name%",
            "device_info":"%device_info%",
            "encrypted_user_id":"%encrypted_user_id%",
            "year_param":"%current_year%"
        },
        "recovery":{
            "site_url":"%site_url%",
            "name_param":"%name%",
            "encrypted_user_id":"%encrypted_user_id%",
            "year_param":"%current_year%"
        }
    }